### Query products over Gateway
GRAPHQL http://localhost:4000/graphql

query ExampleQuery {
    products {
        id
        name
        description
        reviews {
            id
            text
            starRating
        }
    }
}

### query book from products-subgraph
GRAPHQL http://localhost:9080/graphql

query {
  product(id: "1") {
    name
  }
}
