### Query products over Gateway
GRAPHQL http://localhost:4000/graphql

query ExampleQuery {
    products {
        id
        name
        description
        reviews {
            id
            text
            starRating
        }
    }
}